// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/minhhoanq/ecommerce/user_service/internal/dataaccess/database (interfaces: UserDataAccessor)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	database "github.com/minhhoanq/ecommerce/user_service/internal/dataaccess/database"
)

// MockUserDataAccessor is a mock of UserDataAccessor interface.
type MockUserDataAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockUserDataAccessorMockRecorder
}

// MockUserDataAccessorMockRecorder is the mock recorder for MockUserDataAccessor.
type MockUserDataAccessorMockRecorder struct {
	mock *MockUserDataAccessor
}

// NewMockUserDataAccessor creates a new mock instance.
func NewMockUserDataAccessor(ctrl *gomock.Controller) *MockUserDataAccessor {
	mock := &MockUserDataAccessor{ctrl: ctrl}
	mock.recorder = &MockUserDataAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDataAccessor) EXPECT() *MockUserDataAccessorMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockUserDataAccessor) CreateSession(arg0 context.Context, arg1 database.CreateSessionParams) (*database.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(*database.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockUserDataAccessorMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockUserDataAccessor)(nil).CreateSession), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockUserDataAccessor) CreateUser(arg0 context.Context, arg1 database.CreateUserParams) (*database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(*database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserDataAccessorMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserDataAccessor)(nil).CreateUser), arg0, arg1)
}

// CreateUserTx mocks base method.
func (m *MockUserDataAccessor) CreateUserTx(arg0 context.Context, arg1 database.CreateUserTxParams) (database.CreateUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTx", arg0, arg1)
	ret0, _ := ret[0].(database.CreateUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTx indicates an expected call of CreateUserTx.
func (mr *MockUserDataAccessorMockRecorder) CreateUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTx", reflect.TypeOf((*MockUserDataAccessor)(nil).CreateUserTx), arg0, arg1)
}

// CreateVerifyEmail mocks base method.
func (m *MockUserDataAccessor) CreateVerifyEmail(arg0 context.Context, arg1 database.CreateVerifyEmailParams) (*database.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(*database.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerifyEmail indicates an expected call of CreateVerifyEmail.
func (mr *MockUserDataAccessorMockRecorder) CreateVerifyEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerifyEmail", reflect.TypeOf((*MockUserDataAccessor)(nil).CreateVerifyEmail), arg0, arg1)
}

// GetSessionByUserId mocks base method.
func (m *MockUserDataAccessor) GetSessionByUserId(arg0 context.Context, arg1 uuid.UUID) (*database.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByUserId", arg0, arg1)
	ret0, _ := ret[0].(*database.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByUserId indicates an expected call of GetSessionByUserId.
func (mr *MockUserDataAccessorMockRecorder) GetSessionByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByUserId", reflect.TypeOf((*MockUserDataAccessor)(nil).GetSessionByUserId), arg0, arg1)
}

// GetUserByID mocks base method.
func (m *MockUserDataAccessor) GetUserByID(arg0 context.Context, arg1 uuid.UUID) (*database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(*database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserDataAccessorMockRecorder) GetUserByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserDataAccessor)(nil).GetUserByID), arg0, arg1)
}

// GetUserByUsername mocks base method.
func (m *MockUserDataAccessor) GetUserByUsername(arg0 context.Context, arg1 string) (*database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(*database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserDataAccessorMockRecorder) GetUserByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserDataAccessor)(nil).GetUserByUsername), arg0, arg1)
}
