// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/minhhoanq/ecommerce/user_service/internal/dataaccess/kafka/producer (interfaces: UserCreatedProducer)

// Package mockkp is a generated GoMock package.
package mockkp

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	producer "github.com/minhhoanq/ecommerce/user_service/internal/dataaccess/kafka/producer"
)

// MockUserCreatedProducer is a mock of UserCreatedProducer interface.
type MockUserCreatedProducer struct {
	ctrl     *gomock.Controller
	recorder *MockUserCreatedProducerMockRecorder
}

// MockUserCreatedProducerMockRecorder is the mock recorder for MockUserCreatedProducer.
type MockUserCreatedProducerMockRecorder struct {
	mock *MockUserCreatedProducer
}

// NewMockUserCreatedProducer creates a new mock instance.
func NewMockUserCreatedProducer(ctrl *gomock.Controller) *MockUserCreatedProducer {
	mock := &MockUserCreatedProducer{ctrl: ctrl}
	mock.recorder = &MockUserCreatedProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCreatedProducer) EXPECT() *MockUserCreatedProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockUserCreatedProducer) Produce(arg0 context.Context, arg1 producer.UserCreated) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockUserCreatedProducerMockRecorder) Produce(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockUserCreatedProducer)(nil).Produce), arg0, arg1)
}
